import { createLogger, defineConfig, loadEnv, Plugin, UserConfig } from 'vite';
import { viteStaticCopy } from 'vite-plugin-static-copy';
import solidPlugin from 'vite-plugin-solid';
import builtins from 'builtin-modules';
import path from 'path';
import * as fsp from 'fs/promises';



const banner = `
/*!
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository https://github.com/mokeyish/obsidian-enhancing-export .
*/
`;


export default defineConfig(({ mode }) => {
  const prod = mode === 'production';

  const { OUT_DIR } = loadEnv(mode, process.cwd(), ['OUT_']);

  // Defaults to the repository root, so the repo itself is a ready-to-load plugin folder.
  const outDir = path.resolve(process.cwd(), OUT_DIR ? OUT_DIR : '.');
  // manifest.json and styles.css already live in the root, copying them onto
  // themselves would fail. They are only copied when building elsewhere.
  const copyAssets = outDir !== path.resolve(process.cwd());

  return {
    // Vite warns about `outDir` being the root, which is intended here (`emptyOutDir` is off).
    customLogger: silence(/build\.outDir must not be the same directory of root/),
    plugins: [
      solidPlugin(),
      copyAssets ? viteStaticCopy({
        targets: [
          { src: 'manifest.json', dest: '.' },
          { src: 'styles.css', dest: '.' },
        ]
      }) : undefined,
      loader({
        '.lua': 'binary',
        '.tex': 'binary',
        '.sty': 'binary'
      }), // src/resources.ts
      prod ? undefined : inject(['src/hmr.ts']),
    ],
    build: {
      lib: {
        entry: 'src/main.ts',
        name: 'main',
        fileName: () => 'main.js',
        formats: ['cjs'],
      },
      minify: prod,
      sourcemap: prod ? false : 'inline',
      emptyOutDir: false,
      outDir,
      rollupOptions: {
        output: {
          exports: 'named',
          // `banner` is prepended before minification, which drops the comment.
          postBanner: banner,
        },
        external: [
          'obsidian',
          'electron',
          '@codemirror/autocomplete',
          '@codemirror/closebrackets',
          '@codemirror/collab',
          '@codemirror/commands',
          '@codemirror/comment',
          '@codemirror/fold',
          '@codemirror/gutter',
          '@codemirror/highlight',
          '@codemirror/history',
          '@codemirror/language',
          '@codemirror/lint',
          '@codemirror/matchbrackets',
          '@codemirror/panel',
          '@codemirror/rangeset',
          '@codemirror/rectangular-selection',
          '@codemirror/search',
          '@codemirror/state',
          '@codemirror/stream-parser',
          '@codemirror/text',
          '@codemirror/tooltip',
          '@codemirror/view',
          '@lezer/common',
          '@lezer/highlight',
          '@lezer/lr',
          ...builtins
        ],
      },
    }
  } as UserConfig;
});


const silence = (pattern: RegExp) => {
  const logger = createLogger();
  const { warn, warnOnce } = logger;
  logger.warn = (msg, options) => {
    if (!pattern.test(msg)) {
      warn.call(logger, msg, options);
    }
  };
  logger.warnOnce = (msg, options) => {
    if (!pattern.test(msg)) {
      warnOnce.call(logger, msg, options);
    }
  };
  return logger;
};


const loader = (config: { [extention: string]: 'binary' }): Plugin => {
  const { extname } = path;
  return {
    name: 'binary-boader',
    enforce: 'pre',
    async load(id) {
      const format = config[extname(id)];
      if (format) {
        if (format === 'binary') {
          const buffer = await fsp.readFile(id);
          return {
            code: `export default Uint8Array.from(atob('${buffer.toString('base64')}'), c => c.charCodeAt(0));`
          };
        }
      }
    },
  };
};


const inject = (files: string[]): Plugin => {
  if (files && files.length > 0) {
    return {
      name: 'inject-code',
      async load(this, id) {
        const info = this.getModuleInfo(id);
        if (info.isEntry) {
          const code = await fsp.readFile(id, 'utf-8');
          const { relative, dirname, basename, extname, join } = path;
          const dir = dirname(id);
          const inject_code = files
            .map(v => relative(dir, v))
            .map(p => join('./', basename(p, extname(p))))
            .map(p => `import './${p}'`).join(';');
          return `
          ${inject_code};
          ${code}
          `;
        }
      },
    };
  }
};